sanitt/urls.py
from django.conf.urls import url

from . import views

app_name='sanitt'
urlpatterns=[
    url(r'^$',views.index, name='index'),
    url(r'^compound/$',views.searchcompound, name='searchcomp'),
    url(r'^target/$',views.searchtarget, name='detail'),
    url(r'^alltargets/$',views.indextarget, name='alltargets'),
    url(r'^compound/$',views.resultsc, name='resultsc'),
    url(r'^target/id/$',views.detaill, name='detaill'),
    url(r'^ligand/$',views.searchligand, name='ligand'),
    url(r'^ligands/$',views.ligands, name='ligands'),
    url(r'^targets/$',views.targets, name='targets'),
    url(r'^comp/$',views.compound, name='compound'),
    url(r'^contact/$',views.contact, name='contact'),
]

tfm/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^sanitt/', include('sanitt.urls')),
    url(r'^admin/', admin.site.urls),
]

sanitt/models.py
# -*- coding: utf-8 -*-
#from __future__ import unicode_literals

import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

class Target(models.Model):
    tsearch=models.CharField(max_length=20)
    #def __str__(self):
       # return self.tsearch
    target_id= models.IntegerField(default=0)
    nomenclature = models.CharField(max_length=20)
    tname = models.CharField(max_length=200)
    genes = models.CharField(max_length=20)
    ensemblID = models.CharField(max_length=20)
    uniprot = models.CharField(max_length=20)
    #pub_date=models.DateTimeField('date research')
    #def was_research_recently(self):
        #return self.pub_date >= timezone.now()-datetime.timedelta(days=7)

class Protein(models.Model):
    uniprot = models.ForeignKey(Target,on_delete=models.CASCADE)
    bio_process = models.CharField(max_length=200)
    ligand = models.CharField(max_length=50)
    hgng = models.CharField(max_length=20)

class Gene(models.Model):
    hgng = models.ForeignKey(Protein, on_delete=models.CASCADE)
    genetype = models.CharField(max_length=50)
    organism = models.CharField(max_length=50)
    genomic = models.CharField(max_length=50)

class Compound(models.Model):
    csearch = models.CharField(max_length=20)
    #def __str__(self):
       # return self.csearch
    compoundname= models.CharField(max_length=20)
    ccid=models.IntegerField(default=0)
    isomericsmiles=models.CharField(max_length=50)
    
class Compoundcid(models.Model):
    ccid=models.ForeignKey(Compound,on_delete=models.PROTECT)
    molecularformula=models.CharField(max_length=20)
    molecularweight=models.IntegerField(default=0)
    #isomericsmiles=models.ForeignKey(Compound)
    iupacname=models.CharField(max_length=200)
    cxlogp=models.IntegerField(default=0)
    exactmass=models.IntegerField(default=0)
    csynonyms=models.TextField()


#input(str("Ingresa tu búqueda \n")) #Solicitamos datos de entrada
#print ("Tú busqueda es {0}".format(Target)) #Formateamos la salida

sanitt/forms.py
from django import forms

from .models import Compound
from .models import Target

class CompoundForm(forms.Form):
    compoundsearch = forms.CharField(label='Enter name', max_length=100)

class TargetForm(forms.Form):
    tsearch = forms.CharField(label='Enter name', max_length=100)

sanitt/views.py
# -*- coding: utf-8 -*-#
from __future__ import unicode_literals

from django.shortcuts import render

 #Create your views here.#

import requests
import json
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import Target, Protein, Gene, Compound, Compoundcid
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from django.views.decorators.csrf import csrf_protect
#from .forms import CompoundForm, TargetForm
from django.db.models import Q

def index(request):
    return render(request,'sanitt/index.html')

def targets(request):
    return render(request,'sanitt/targets.html')

def ligands(request):
    return render(request,'sanitt/ligands.html')

def compound(request):
    return render(request,'sanitt/compound.html')

def contact(request):
    return render(request,'sanitt/contact.html')

def searchcompound(request):
    query = request.GET.get('q', '')
    if query:
        datos=requests.get("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/%s/cids/json?list_return=flat" %query)
        compounds=datos.json()
        ccids=compounds["IdentifierList"]["CID"]
        for ccid in ccids:
            compmf=requests.get("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/%s/property/MolecularFormula/json" %ccid)
            mf=compmf.json()
            molecularformula=mf["PropertyTable"]["Properties"][0]["MolecularFormula"]
            compmw=requests.get("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/%s/property/MolecularWeight/json" %ccid)
            mw=compmw.json()
            molecularweight=mw["PropertyTable"]["Properties"][0]["MolecularWeight"]
            compis=requests.get("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/%s/property/IsomericSMILES/json" %ccid)
            ism=compis.json()
            isomericsmiles=ism["PropertyTable"]["Properties"][0]["IsomericSMILES"]
            compin=requests.get("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/%s/property/IUPACName/json" %ccid)
            ina=compin.json()
            iupacname=ina["PropertyTable"]["Properties"][0]["IUPACName"]
            compxl=requests.get("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/%s/property/XLogP/json" %ccid)
            xl=compxl.json()
            cxlogp=xl["PropertyTable"]["Properties"][0]["XLogP"]
            compem=requests.get("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/%s/property/ExactMass/json" %ccid)
            em=compem.json()
            exactmass=em["PropertyTable"]["Properties"][0]["ExactMass"]
            compdesc=requests.get("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/%s/description/json" %ccid)
            desc=compdesc.json()
            description=desc["InformationList"]["Information"][2]["Description"]
            compsyn=requests.get("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/%s/synonyms/json" %ccid)
            syn=compsyn.json()
            synonyms=syn["InformationList"]["Information"][0]["Synonym"][5]           
                   
        return render(request,'sanitt/searchcomp.html',{'query':query, 'ccids':ccids, 'ccid':ccid, 'molecularformula':molecularformula, 'molecularweight':molecularweight, 'isomericsmiles':isomericsmiles, 'iupacname':iupacname, 'cxlogp':cxlogp, 'exactmass':exactmass, 'description':description, 'synonyms':synonyms})

    else:

        return HttpResponse('/doesntwork/')

    return render(request,'sanitt/searchcomp.html')



def searchtarget(request):
    tquery = request.GET.get('t', '') 
    if tquery:
        mytarget=requests.get("https://www.guidetopharmacology.org/services/targets?name=%s" %tquery)
        tid=mytarget.json()
        target_id=tid[0]["targetId"]
        tname=tid[0]["name"]
        ttype=tid[0]["type"]
        nomenclature=tid[0]["abbreviation"]
        tfamily=tid[0]["familyIds"][0]
        myfamily=requests.get("https://www.guidetopharmacology.org/services/targets/families/%s" %tfamily)
        tf=myfamily.json()
        tfname=tf["name"]
        genes=requests.get("https://www.guidetopharmacology.org/services/targets/%s/geneProteinInformation" %target_id)
        tgen=genes.json()
        gensp=tgen[0]["species"]
        gensym=tgen[0]["geneSymbol"]
        genname=tgen[0]["geneName"]
        tuni=requests.get("https://www.guidetopharmacology.org/services/targets/%s/databaseLinks?database=uniprotkb" %target_id)
        tunip=tuni.json()
        uniprot=tunip[0]["accession"]
        tense=requests.get("https://www.guidetopharmacology.org/services/targets/%s/databaseLinks?database=Ensembl Gene" %target_id)
        tensem=tense.json()
        ensembl=tensem[0]["accession"]
        contextt={
        'tquery':tquery,
        'tname':tname,
        'target_id':target_id,
        'ttype':ttype,
        'nomenclature':nomenclature,
        'tfamily':tfamily,
        'tfname': tfname,
        'gensp':gensp,
        'gensym':gensym,
        'genname':genname,
        'uniprot':uniprot,
        'ensembl':ensembl,
            }
        return render(request,'sanitt/detail.html',contextt)
  
    else:
        return render(request,'sanitt/detail.html')

        
        

def indextarget(request):
    all_targets = pygtop.get_all_targets()
    len_targets = len(all_targets)
    latest_target_list=Target.objects.order_by('-tname')[:5]
    context={
        'latest_target_list': latest_target_list, 
        'all_targets': all_targets,
        'len_targets': len_targets
         } 
    return render(request,'sanitt/alltargets.html',context)

def detaill(request):
    targetid= request.GET.get('tid', '')
    ligandmy=requests.get("https://www.guidetopharmacology.org/services/targets/%s/interactions" %targetid)
        #return render(request,'sanitt/detaill.html',{'targetid':targetid, 'nligand_id': nligand_id, 'nligand_name': nligand_name, 'nlnomenclature': nlnomenclature, 'nltype': nltype })
    #else:
        #return render(request,'sanitt/detaill.html')
    #if ligandmy.status_code == 200:
    limy=ligandmy.json()
    interactionid=limy[0]["interactionId"]
    iligand_id=limy[0]["ligandId"]
    iligandn=requests.get("https://www.guidetopharmacology.org/services/ligands/%s/" %iligand_id)
    ilname=iligandn.json()
    iligandname=ilname["name"]
    itype=limy[0]["type"]
    iaction=limy[0]["action"]
    iaffinity=limy[0]["affinity"]
    iaffinityp=limy[0]["affinityParameter"]
    mydis=requests.get("https://www.guidetopharmacology.org/services/targets/%s/diseases" %targetid)
    mypdb=requests.get("https://www.guidetopharmacology.org/services/targets/%s/pdbStructure" %targetid)
    #if mydis.status_code == 200:
    dis=mydis.json()
    dis_id=dis[0]["disease"]["diseaseId"]
    disname=dis[0]["disease"]["name"]
    drug=dis[0]["drugs"]
        #return render(request,'sanitt/detaill.html',{'targetid':targetid, 'dis_id':dis_id, 'disname':disname, 'drug':drug})
    #else:
        #dis_id="not found result"
        #disname="not found result"
       # drug="not found result"
        #return render(request,'sanitt/detaill.html',{'targetid':targetid, 'dis_id':dis_id, 'disname':disname, 'drug':drug})
    #if mypdb.status_code == 200: 
    mpdb=mypdb.json()
    pdb_id=mpdb[0]["pdbCode"]
    pdb_descrip=mpdb[0]["description"]
    pdb_resolution=mpdb[0]["resolution"]
    pdb_specie=mpdb[0]["species"]
    #else:
        #pdb_id="not found result"
        #pdb_descrip="not found result"
        #pdb_resolution="not found result"
        #pdb_specie="not found result"
        #return render(request,'sanitt/detaill.html',{'targetid':targetid, 'pdb_id':pdb_id, 'pdb_descrip':pdb_descrip,  'pdb_resolution':pdb_resolution, 'pdb_specie':pdb_specie})
    contextd={'targetid':targetid, 'interactionid':interactionid, 'iligand_id':iligand_id ,'iligandname':iligandname , 'itype':itype , 'iaction':iaction, 'iaffinity':iaffinity, 'iaffinityp':iaffinityp, 'pdb_id':pdb_id, 'pdb_descrip':pdb_descrip,  'pdb_resolution':pdb_resolution, 'pdb_specie':pdb_specie,'dis_id':dis_id, 'disname':disname, 'drug':drug}
    return render(request, 'sanitt/detaill.html', contextd)
   # else:
       # return render(request, 'sanitt/detaill.html')

def searchligand(request):
    lquery = request.GET.get('l', '') 
    if lquery:
        myligand=requests.get("https://www.guidetopharmacology.org/services/ligands?name=%s" %lquery)
        ligand=myligand.json()
        ligandid=ligand[0]["ligandId"]
        ligandname=ligand[0]["name"]
        ligandnomcl=ligand[0]["abbreviation"]
        ligandtype=ligand[0]["type"]
        ligandpdb=requests.get("https://www.guidetopharmacology.org/services/ligands/%s/databaseLinks?database=Pubchem CID" %ligandid)
        lpdb=ligandpdb.json()
        lcid=lpdb[0]["accession"]
        lcompmf=requests.get("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/%s/property/MolecularFormula/json" %lcid)
        lmf=lcompmf.json()
        lmolecularformula=lmf["PropertyTable"]["Properties"][0]["MolecularFormula"]
        lcompmw=requests.get("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/%s/property/MolecularWeight/json" %lcid)
        lmw=lcompmw.json()
        lmolecularweight=lmw["PropertyTable"]["Properties"][0]["MolecularWeight"]
        lcompis=requests.get("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/%s/property/IsomericSMILES/json" %lcid)
        lism=lcompis.json()
        lisomericsmiles=lism["PropertyTable"]["Properties"][0]["IsomericSMILES"]
        lcompin=requests.get("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/%s/property/IUPACName/json" %lcid)
        lina=lcompin.json()
        liupacname=lina["PropertyTable"]["Properties"][0]["IUPACName"]
        lcompxl=requests.get("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/%s/property/XLogP/json" %lcid)
        lxl=lcompxl.json()
        lcxlogp=lxl["PropertyTable"]["Properties"][0]["XLogP"]

sanitt/templates/sanitt/alltargets.html
<!DOCTYPE html>
<html >
<head>
<meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<title>APP SANITT</title>
{% load static %}
<link rel="stylesheet" type= "text/css" href="{% static 'sanitt/style.css'%}"/>
</head>



<body>

<!-- Start of Page Header -->
<div id="page_header">
<div id="page_heading">
<h1><br>APP SANITT<br></h1>
<h2><br>eslogan</h2>
</div>
<div id="page_headerlinks">
<ul>
<li><a href="">ES</li>
<li><a href="">CAT</li>
<li><a href="">EN</li>
<li><a href="">Help</li>
<li class="last"><a href="">Contact</a></li>
</ul>
</div>
<div id="page_headersearch">

<div class="clearthis">&nbsp;</div>
</div>
</form>
</div>
<div class="clearthis">&nbsp;</div>
</div>
<!-- End of Page Header --><!-- Start of Page Menu -->
<div id="page_menu">
<ul>
<li><a href="">Aplication</a></li>
<li><a href="">Targets</a></li>
<li><a href="">Ligands</a></li>
<li><a href="">Genes</a></li>
<li><a href="">Drugs</a></li>
<li><a href="">Compound</a></li>
<li class="last">Contact</li>
</ul>
</div>
<!-- End of Page Menu --><!-- Start of Left Sidebar -->
<div id="left_sidebar"></div>
<!-- End of Left Sidebar -->
<!-- Start of Main Content Area -->
<div id="main_content">
<ul>
<li>
<!-- Start of New Item Description -->
<div id="new_item"></div>
{% if all_targets %}
    <ul>
        <li>The number of targets in data base is {{len_targets}}
<br><br>
<a href="https://www.guidetopharmacology.org/services/targets/families">View Families</a></li>

    </ul>
{% else %}
    <p>No targets are available</p>
{%endif%}
<div id="new_item_header">
<h1>TARGET</h1>
<h2>yyyyy</h2>
</div>
<div id="new_item_image">  </div>
<div id="new_item_text">
{% if latest_target_list %}
    <ul>
    {% for target in latest_target_list %}
        <li><a href="/sanitt/target/{{target.id}}/">{{target.target_id}}</a><br><a href="https://www.guidetopharmacology.org/services/targets/{{target.target_id}}">Visit Iuphar</a></li>
    {% endfor%}
    </ul>
{% else %}
    <p>No targets are available</p>
{%endif%}

</div></div>


<h2>Target search:</h2>

<form action="." method="get">
{{ form.target}}
{% csrf_token %}
    <label>Enter name: </label>
    <input id= "tsearch" type="text" name="searchString" placeholder="name of target">
    <input type="submit" value="Search">
</form>
{% if tname_list %}
<ul>
<li><a href="https://www.guidetopharmacology.org/services/targets/{{target.target_id}}">{{target.target_id}}</a></li>
<li>{{target.target_id}}</li>
</ul>
</div>
{% else %}
    <p>No targets are available</p>
{%endif%}


<!-- End of New Item Description -->
<div class="h_divider">&nbsp;</div>

<!-- Start of Page Footer -->

<!-- End of Page Footer --><!-- End of Main Content Area --></div>
</body></html>

sanitt/templates/sanitt/base.html
<!DOCTYPE html>
<html >
<head>
<meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<title>APP SANITT</title>
{% load static %}
<link rel="stylesheet" type= "text/css" href="{% static 'sanitt/style.css'%}"/>
</head>



<body>

<!-- Start of Page Header -->
<div id="page_header">
<div id="page_heading">
<h1><img src="{% static 'sanitt/sanitt.png'%}" width="100"></h1>
<h2><br>Find your molecule</br></h2>
</div>
<div id="page_headerlinks">
<ul>
<li>EN</li>
<li><a href={% url 'sanitt:contact' %}>Help</li>
<li class="last"><a href={% url 'sanitt:contact' %}>Contact</a></li>
</ul>
</div>
<div class="clearthis">&nbsp;</div>


<div class="clearthis">&nbsp;</div>
</div>
<!-- End of Page Header --><!-- Start of Page Menu -->
<div id="page_menu">
<ul>
<li><a href={% url 'sanitt:index' %}>Home</a></li>
<li><a href={% url 'sanitt:targets' %}>Targets</a></li>
<li><a href={% url 'sanitt:ligands' %}>Ligands</a></li>
<li><a href="">Genes</a></li>
<li><a href="">Drugs</a></li>
<li><a href={% url 'sanitt:compound' %}>Compound</a></li>
<li><a href={% url 'sanitt:contact' %}>Contact</a></li>
</ul>
</div>
<!-- End of Page Menu --><!-- Start of Left Sidebar -->
<!-- End of Left Sidebar -->
<!-- Start of Main Content Area -->
<div id="main_content"></div>
{% block content %}
{% endblock %}


<!-- End of New Item Description -->
<div class="h_divider"> </div>

<!-- Start of Page Footer -->
<div class= product_brands>

</div>

<!-- End of Page Footer --><!-- End of Main Content Area --></div>
</body></html>

sanitt/templates/sanitt/compound.html
{% extends 'sanitt/base.html' %}
{% block content %}
<!-- Start of New Item Description -->
<div id="new_item">
<div id="new_item_header">
<h1> Compound Search</h1></div>
<div id="new_item_image"></div>
<div id="new_item_text">
<br>
<br>
<h2>Compound search:</h2>
<p> Search for your chemical compound by name (example:aspirin, ibuprofen, ..)</p>
<form action={% url 'sanitt:searchcomp' %} method='get'>{% csrf_token %}
<label for="q"></label>
<input type="text" name="q" value="{{ query }}">
<input type="submit" value="Search">
</form>
<br>
<br>
<br>
<br>


</div></div>
 
{%endblock%}

sanitt/templates/sanitt/contact.html
{% extends 'sanitt/base.html' %}
{% block content %}
<!-- Start of New Item Description -->
<div id="new_item">
<div id="new_item_header">
<h1> Contact</h1></div>
<div id="new_item_image"></div>
<div id="new_item_text">
<br>
<p>Contact with the following e-mail in case you need help or communicate any incidence</p>
<br>
<h3>e-mail: srochas@uoc.edu </h3>
<br>
<br>
<p>Thanks</p>
<br>
<br>


</div></div>
 
{%endblock%}

sanitt/templates/sanitt/detail.html
{% extends 'sanitt/base.html'%}
{% block content %}
<!-- Start of New Item Description -->
<div id="new_item"></div>
{% if tquery %}
<div id="new_item_header">
<h2>Search of results Target: {{tquery}}</h2>
</div>
<div id="new_item_image">  </div>

<div id="new_item_text">

<br>
<br>
    <table>
        <tr>
        <td>Target ID</td><td>{{target_id}}</td>
        </tr>
        <tr>
        <td>Type</td><td>{{ttype}}</td>
        </tr>
        <tr>
        <td>Name</td><td>{{tname}}</td>
        </tr>
        <tr>
        <td>Nomenclature</td><td>{{nomenclature}}</td>
        </tr>
        <tr>
        <td>Family ID</td><td>{{tfamily}}</td>
        </tr>
    </table>
<br>
<br>
<br>
    <table>
        <tr>
        <td>Gene Species</td><td>{{gensp}}</td>
        </tr>
        <tr>
        <td>Gene Symbol</td><td>{{gensym}}</td>
        </tr>
        <tr>
        <td>Gene Name</td><td>{{genname}}</td>
        </tr>
    </table>
<br>
<br>
<br>
    <table>
        <tr>
        <td>Uniprot</td><td><a href="http://www.uniprot.org/uniprot/{{uniprot}}">{{uniprot}}</a></td>
        </tr>
        <tr>
        <td>Ensembl Gene</td><td><a href="http://www.ensembl.org/Gene/Summary?g={{ensembl}}">{{ensembl}}</a> </td>
        </tr>
    </table>
{% else %}
<h4> Not found results </h4>
<p> <a href="index">try again</a> or:</p>
{% endif %}
<br>
<br>
<br>
<h2>Search by targetId to see more results:</h2>

<form action={% url 'sanitt:detaill' %}  method='get'>{% csrf_token %}
    <label for="tid" >Search: </label>
    <input name= "tid" type="text" value="{{ targetid }}">
    <input type="submit" value="Search">
</form>
<br>
<br>
<br>

<br>
<br>
<br>
</div></div>
{% endblock %}

sanitt/templates/sanitt/index.html
{% extends 'sanitt/base.html' %}
{% block content %}
<!-- Start of New Item Description -->
<div id="new_item">
<div id="new_item_header">
<h1> Search page</h1></div>
<div id="new_item_image"></div>
<div id="new_item_text">
<p> Welcome to the SANITT application, this application has been created with the intention of providing in the same search the information of several databases, among them IUPHAR, PDB and PubChem.</p>
<br>
<br>
<h2>Compound search:</h2>
<p> Search for your chemical compound by name</p>
<form action={% url 'sanitt:searchcomp' %} method='get'>{% csrf_token %}
<label for="q"></label>
<input type="text" name="q" value="{{ query }}">
<input type="submit" value="Search">
</form>
<br>
<br>
<br>
<br>
<h2>Target search:</h2>
<p> Search for your target by name</p>
<form action={% url 'sanitt:detail' %}  method='get'>{% csrf_token %}
    <label for="t" ></label>
    <input name= "t" type="text" value="{{ tquery }}">
    <input type="submit" value="Search">
</form>

<br>
<br>
<br>
<br>

<h2>Ligand search:</h2>
<p> Search for your ligand by name</p>
<form action={% url 'sanitt:ligand' %}  method='get'>{% csrf_token %}
    <label for="l" ></label>
    <input name= "l" type="text" value="{{ lquery }}">
    <input type="submit" value="Search">
</form>

</div></div>
 
{%endblock%}

sanitt/templates/sanitt/ligands.html
{% extends 'sanitt/base.html' %}
{% block content %}
<!-- Start of New Item Description -->
<div id="new_item">
<div id="new_item_header">
<h1> What is a ligand?</h1></div>
<div id="new_item_image"></div>
<div id="new_item_text">
<p> In biochemistry and pharmacology, a ligand is a substance that forms a compound with a biomolecule to perform a biological function. In protein-ligand interaction, the ligand is usually a molecule that produces a signal by binding to a specific location on a target protein. 

Bonding occurs by intermolecular forces, such as ionic bonds, hydrogen bonds, and Van der Waals forces. The coupling association is reversible through dissociation. 

Ligand binding to a receptor protein alters conformation by affecting the orientation of the three-dimensional shape. The conformation of a receptor protein composes the functional state. 

Ligands include substrates, inhibitors, activators, signaling lipids, and neurotransmitters. The rate of binding is called affinity, and this measure tells us a trend or strength of the effect. In the binding affinity along with host-host interactions the effects of the solvent are also important, as it provides a chemical environment for the ligand and receptor to accept or reject each other.
 </p>
<br>
<br>

<h2>Ligand search:</h2>
<p> Search for your ligand by name</p>
<form action={% url 'sanitt:ligand' %}  method='get'>{% csrf_token %}
    <label for="l" ></label>
    <input name= "l" type="text" value="{{ lquery }}">
    <input type="submit" value="Search">
</form>

</div></div>
 
{%endblock%}

sanitt/templates/sanitt/targets.html
{% extends 'sanitt/base.html' %}
{% block content %}
<!-- Start of New Item Description -->
<div id="new_item">
<div id="new_item_header">
<h1> What is a target protein?</h1></div>
<div id="new_item_image"></div>
<div id="new_item_text">
<p> Target proteins are functional biomolecules directed and controlled by biologically active compounds. They are used in the processes of transduction, transformation and conjugation. Target protein identification, research and interaction with ligands are key elements of modern biomedical research. Since interaction with target proteins is the molecular origin of most drugs, it is of great importance to molecular biology, molecular pharmacy and pharmaceutical sciences. 
Target proteins control the action and kinetic activity of drugs in the body. 
Target proteins can also be drugs themselves when their modification and formulation is emphasized within the pharmaceutical sciences. </p>
<br>
<br>

<h2>Target search:</h2>
<p> Search for your target by name</p>
<form action={% url 'sanitt:detail' %}  method='get'>{% csrf_token %}
    <label for="t" ></label>
    <input name= "t" type="text" value="{{ tquery }}">
    <input type="submit" value="Search">
</form>



</div></div>
 
{%endblock%}